export const ADD_ITEM = 'ADD_ITEM';
export const CANCEL_EDIT_ITEM = 'CANCEL_EDIT_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';
export const EDIT_ITEM = 'EDIT_ITEM';
export const ITEM_COMPLETION = 'ITEM_COMPLETION';
export const LOAD_STATE_LOCALSTORAGE = 'LOAD_STATE_LOCALSTORAGE';
export const REORDER_ITEM = 'REORDER_ITEM';
export const SAVE_STATE_LOCALSTORAGE = 'SAVE_STATE_LOCALSTORAGE';
export const SELECT_EDIT_ITEM = 'SELECT_EDIT_ITEM';


